### ISSUE TITLE
Can't deploy to beanstalk anymore

### ISSUE THREAD

**Issue by haskins-io** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#22] opened 2014-09-25 10:53 UTC
Hi,

not sure if I need to be raising this with you or the PyCharm dev so I'm informing everyone.

I'm running on a mac (10.9.4), using PyCharm PY-135.1057, version 0.6.6 of the plugin

I've been using the plugin to deploy to Beanstalk on a regular basis, though this stopped working on Monday morning. The only thing that I can think of that has changed is that I updated Xcode to the latest version, no other changes (Java, PyCharm, etc) had been made.

When I try and deploy now it just hangs, I can see git commands in the logs which look to be trying to push to AWS but nothing happens. In the ide the spinning activity indicator in the Application Severs tool window just hangs.

Now if I try and deploy to an unknown environment, I'm told it doesn't exist, so the plugin is communicating with AWS, just the deployment part isn't working. If I log into the AWS Web Console and watch the environment there is no indication that it has received a new Application Version and the environment is updating.

Any ideas?

Mark

**Comment by viatra2** [comment] 2014-09-27 11:09
Hello, thank you for using our plugin on a regular basis.
Unfortunately we can't reproduce your issue with PyCharm 3.4.1 (135.1057) and plugin version 0.6.6.

Please do following steps to provide additional information:
1. Enable plugin debug output by appending following at the end of the "_PyCharm_home_\bin\log.xml" (before the closing _log4j:configuration_ tag):
`<category name="#com.viatra2.cloud.imported.CloudMultiSourceServerRuntimeInstance">
    <priority value="DEBUG"/> <appender-ref ref="CONSOLE-ALL"/>
  </category>`
2. Restart PyCharm
3. Launch your Elastic Beanstalk run configuration and wait until it finishes
4. Attach produced PyCharm log (Help -> Show Log...)
5. Attach complete textual output of the Application Servers tab (if any)

Regards, 
Viatra2

**Comment by haskins-io** [comment] 2014-09-29 10:08
Well this is annoying.

I haven't been able deploy Beanstalk applications all last week, I tried several times and nothing happened, so I raised this issue. 

I haven't turned my laptop on over the weekend, and yet when I added the extra bit to the log4j config file and ran a test to generate a log file for you, it worked first time.

Not sure what to say other than, thanks for getting back to me, and it would seem that I've wasted your time.

Regards,

Mark

**Comment by viatra2** [comment] 2014-09-29 10:28
You are welcome!

Please don't hesitate to post feature requests and bug reports. We are happy to hear your feedback.

If this problem will appear again - please reopen this issue and don't forget to append plugin debug output as described above.

Regards, 
Viatra2

**Closed as completed by viatra2** 2014-09-29 10:28 UTC
Labels: invalid
