### ISSUE TITLE
S3 location error

### ISSUE THREAD

**Issue by awaddell** [viatra2/IDEA-AWS-Elastic-Beanstalk-Integration#2] opened 2013-07-18 15:55 UTC
Hi - thanks for the Java 6 build. Got this error for you...

2013-07-19 01:44:13,894 [ 522490]  ERROR - erver.JavaeeServerInstanceImpl - The unspecified location constraint is incompatible for the region specific endpoint this request was sent to. 
Status Code: 400, AWS Service: Amazon S3, AWS Request ID: 2528A2C58B2ED5B3, AWS Error Code: IllegalLocationConstraintException, AWS Error Message: The unspecified location constraint is incompatible for the region specific endpoint this request was sent to., S3 Extended Request ID: 5Dl1yaYL+hPhQqbMIkmcPV/uBruU+MCox9XtqC7YzTAeAxJIjE6fBtlVNNjP4Z2G
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:640)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:338)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:190)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:2966)
    at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:630)
    at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:552)
    at com.intellij.javaee.awselasticbeanstalk.agent.EBAgent$Deployer.getOrCreateS3Bucket(EBAgent.java:425)
    at com.intellij.javaee.awselasticbeanstalk.agent.EBAgent$Deployer.deploy(EBAgent.java:324)
    at com.intellij.javaee.awselasticbeanstalk.agent.EBAgent.startDeploy(EBAgent.java:95)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.javaee.oss.agent.ReflectiveAgentProxyFactory$ReflectiveInvocationHandler.invoke(ReflectiveAgentProxyFactory.java:91)
    at com.sun.proxy.$Proxy104.startDeploy(Unknown Source)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.intellij.javaee.oss.agent.ThreadAgentProxyFactory$ThreadInvocationHandler$1.call(ThreadAgentProxyFactory.java:169)
    at com.intellij.javaee.oss.agent.ThreadAgentProxyFactory$ThreadInvocationHandler$2.run(ThreadAgentProxyFactory.java:191)
    at com.intellij.javaee.util.SequentialTaskExecutor$1.run(SequentialTaskExecutor.java:32)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:454)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:680)
    at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:152)
2013-07-19 01:44:13,895 [ 522491]  ERROR - erver.JavaeeServerInstanceImpl - IntelliJ IDEA 12.1.4  Build #IU-129.713 
2013-07-19 01:44:13,896 [ 522492]  ERROR - erver.JavaeeServerInstanceImpl - JDK: 1.6.0_51 
2013-07-19 01:44:13,896 [ 522492]  ERROR - erver.JavaeeServerInstanceImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2013-07-19 01:44:13,896 [ 522492]  ERROR - erver.JavaeeServerInstanceImpl - Vendor: Apple Inc. 
2013-07-19 01:44:13,896 [ 522492]  ERROR - erver.JavaeeServerInstanceImpl - OS: Mac OS X 
2013-07-19 01:44:13,896 [ 522492]  ERROR - erver.JavaeeServerInstanceImpl - Last Action: Run

**Comment by viatra2** [comment] 2013-07-19 09:26
Hello!

It appears that there is a bug in IDEA code that checks whether the downloaded library files should be updated. It looks like IDEA still assumes that the libs version 1.3.33 that were downloaded for previous version of plugin are still fine, even also we instructed it to download new versions 1.5.0.

It is difficult to fix this from the our side so we will talk to IDEA guys soon. 

As a workaround, you may:
1) Close IntelliJ IDEA
2) Delete "client" libraries folder in <user home>.IntelliJIdea12\system\AwsElasticBeanstalkClientLibrary
3) Start IntelliJ IDEA
4) Go to "Run\Debug configuration" -> "Configure" and redownload client libraries by pressing "Download AWS SDK"

**Comment by viatra2** [comment] 2013-07-19 11:13
The issue is fixed in the version 0.5.4

**Closed as completed by viatra2** 2013-07-19 11:13 UTC
Labels: bug

**Comment by awaddell** [comment] 2013-07-20 18:54
Hi, I can report that on starting IDEA I received a prompt for the new plugin version 0.5.4 and after restarting a 'fix' option for the newer AWS classes so all very smooth. Elastic Beanstalk launched with the demo app with no problems at all. 
Thanks again.

**Comment by danigonzalez** [comment] 2015-04-15 19:26
Hi, got this error today after intelliJ and plugin update. It was working two months ago with old versions of intelliJ and the plugin. Thanks!

Deploying 'stl-compagnon-prod'...
Failed to deploy 'stl-compagnon-prod': com.amazonaws.services.s3.model.AmazonS3Exception: The specified location-constraint is not valid (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: 5009F798FD79957E), S3 Extended Request ID: IDQT9DxBS6gjh9i1/2Z7j5Xrzgirac6v0pduWbLqiZlJkRDNBUctnkTI+WDINNnL

**Comment by viatra2** [comment] 2015-04-17 17:34
Hello!

@danigonzalez 
Please provide additional info:
What region do you use?
What is your platform?
If your platform is Java-based (Tomcat or GlassFish), do you deploy exploded or archive artifact?

**Comment by jamespauly** [comment] 2015-04-23 15:03
I'm having the same issue.  I'm using us-east-1 and this is a Tomcat 7 Java 7 application and I'm deploying the war.

Deploying 'TIPDashboard:war'...
Failed to deploy 'TIPDashboard:war': com.amazonaws.services.s3.model.AmazonS3Exception: The specified location-constraint is not valid (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: xxxxxxxx), S3 Extended Request ID: xxxxxxxx

**Comment by priyankmundragmail** [comment] 2015-08-11 02:28
did u ever got around this issue ?

**Comment by viatra2** [comment] 2015-08-11 16:29
I'm unable to reproduce the issue anymore.

Please provide additional info:
1) What region do you use?
2) What is your platform?
3) If your platform is Java-based (Tomcat or GlassFish), do you deploy exploded or archive artifact?
4) Which S3 buckets are used (elasticbeanstalk-eu-west-1 etc)
5) Do you use IAM roles?

**Comment by priyankmundragmail** [comment] 2015-08-11 19:24
yeah,..i just had to restart my workspace and it worked alright

**Comment by jamespauly** [comment] 2015-08-11 20:44
Okay let me give it a shot and I’ll let you know.

From:  priyankmundragmail
Reply-To:  viatra2/IDEA-AWS-Elastic-Beanstalk-Integration
Date:  Tuesday, August 11, 2015 at 3:24 PM
To:  viatra2/IDEA-AWS-Elastic-Beanstalk-Integration
Cc:  James Paul
Subject:  Re: [IDEA-AWS-Elastic-Beanstalk-Integration] S3 location error (#2)

yeah,..i just had to restart my workspace and it worked alright

**Comment by neeagl** [comment] 2016-08-25 17:36
Hey, it is not working for me today. Tried restarting etc. as mentioend above but nothing worked.
Intelli build 141.3058
Region: us-east-1
Mac
Tomcat 8 Java 8

**Comment by arthurvernon** [comment] 2017-01-23 01:18
I have also hit this issue. As a new user, I first attempted to deploy a war file (unexploded) to us-east-1. Was attempting to deploy to a Tomcat-8 container running on Java 8. This failed. I restarted as suggested above and retried. Not good. Only after then attempting to deploy as an exploded war did it work.
As an aside, there is a filed on the war configuration where an IAM role can be entered. For some reason, I have no roles to select from. Is there any specified permissions that are required for the IAM user created in the first instance?

**Comment by securelord** [comment] 2017-01-25 11:15
Hi @arthurvernon.
I tried to reproduce the deploy process using your settings.
To do this, I took a simple Java Web project, created from it war-file and deploy it on **us-east-1** with the following settings: **Java8, Tomcat8**.
Your problem is not reproduced.
I need a screenshot **run-configuration** and what type of project you are creating.

**Comment by shamsuvs** [comment] 2017-09-21 17:02
Hello  I am also facing issue
ailed to deploy 'awsexp': com.amazonaws.services.s3.model.AmazonS3Exception: The specified location-constraint is not valid (Service: Amazon S3; Status Code: 400; Error Code: InvalidLocationConstraint; Request ID: 49A137119D106EDF), S3 Extended Request ID: PoJPLuYy7g/EELsUI5gUEpNaCcfIV2jmtdmWk6Fdn6hlwEc54ChGs0pAOgr+oneUFdIrOdmwLsw=
[
<img width="1251" alt="screen shot 2017-09-21 at 9 02 03 pm" src="https://user-images.githubusercontent.com/4375386/30708505-34d86806-9f10-11e7-92bf-4cc19ca50784.png">
](url)
